// Build-time only: never imported by the Cloudflare Worker.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, extname } from 'node:path'
import { transform } from 'esbuild'

async function minify(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) { await minify(path); continue }
    const ext = extname(path)
    if (!['.js', '.css'].includes(ext)) continue
    const source = await readFile(path, 'utf8')
    const result = await transform(source, { loader: ext === '.css' ? 'css' : 'js', minify: true, target: 'es2020', legalComments: 'inline' })
    await writeFile(path, result.code)
  }
}
if (process.argv.includes('--prepare')) {
  const parts = await Promise.all(['fonts/fonts.css', 'fonts/icons.css', 'style.css'].map(file => readFile('public/static/' + file, 'utf8')))
  const source = parts.join('\n').replaceAll("url('./", "url('/static/fonts/")
  const { code } = await transform(source, { loader: 'css', minify: true, target: 'es2020' })
  await writeFile('src/styles.generated.ts', '// Generated by scripts/optimize-assets.mjs --prepare; edit public/static sources instead.\nexport const siteStyles = ' + JSON.stringify(code) + '\n')
  console.log('Generated inline styles to remove render-blocking stylesheet requests.')
} else {
  await minify('dist/static')
  console.log('Static JS/CSS minified; original source and font licenses preserved.')
}
